name: MooTools-DatePicker
author: astolwijk
current: 1.50b3
category: Widgets
tags: [Datepicker,Calendar]
demo: http://www.aryweb.nl/projects/mootools-datepicker/
docs: http://github.com/arian/mootools-datepicker/blob/master/README.md